dashboard/urls.py
from django.urls import path
from . import views, apis
from django.contrib.auth.decorators import login_required

from django.conf.urls import url

urlpatterns = [
        path('', views.home, name='home'),
        path('shop/bookings', views.shop_bookings, name='shop-bookings'),
        path('shop/bookings/previous/', views.shop_bookings_completed, name='shop-bookings-completed'),
        path('shop/bookings/<int:booking_id>/', views.shop_view_booking, name='shop-view-booking'),

        path('shop/account', views.shop_account, name='shop-account'),

        path('shop/services', views.shop_services, name='shop-services'),
        path('shop/services/add/', views.shop_add_services, name='shop-add-services'),
        path('shop/services/edit/<int:service_id>/', views.shop_edit_services, name='shop-edit-services'),
        path('shop/services/album/<int:service_id>/', views.shop_service_album, name='shop-service-album'),

        path('shop/reports', views.shop_reports, name='shop-reports'),
        path('shop/employees', views.shop_employees, name='shop-employees'),
        url(r'^api/booking/notification/(?P<last_request_time>.+)/$', apis.shop_booking_notification),

        path('api/booking/get/<int:booking_id>/', apis.get_booking),

        #CUSTOMER API'S
        path('api/customer/stripe/', apis.stripe_ephemeral_key),
        path('api/customer/stripe/secret/', apis.get_stripe_client_secret),
        path('api/customer/shops/<int:filter_id>/', apis.customer_get_shops),
        path('api/customer/services/<int:filter_id>/<int:shop_id>/', apis.customer_get_services),
        path('api/customer/service/album/<int:service_id>/', apis.customer_get_service_album),
        path('api/customer/booking/add/', apis.customer_add_booking),
        path('api/customer/bookings/<int:filter_id>/', apis.customer_get_bookings),
        path('api/customer/shop/updaterating/', apis.customer_update_ratings),

        path('api/customer/booking/cancel/<int:booking_id>/', apis.customer_cancel_booking),
        path('api/customer/employee/location/', apis.customer_employee_location),

        path('api/customer/getinfo/', apis.customer_get_details),
        path('api/customer/updateinfo/', apis.customer_update_details),

        path('api/check/last-logged-in-as/', apis.check_user_last_loggin_in_as),
        path('api/set/last-logged-in-as/', apis.set_user_last_loggin_in_as),

        
        path('api/beamstoken/', apis.get_beam_token),

        ##EMPLOYEE API'S
        path('api/employee/getinfo/', apis.employee_get_details),
        path('api/employee/updateinfo/', apis.employee_update_details),

        path('api/employee/verify/', apis.employee_verify),
        path('api/employee/bookings/<int:filter_id>/', apis.employee_get_bookings),
        path('api/employee/booking/accept/', apis.employee_accept_booking),
        path('api/employee/booking/decline/', apis.employee_decline_booking),
        path('api/employee/booking/enroute/', apis.employee_enroute),
        path('api/employee/booking/info/<int:booking_id>/', apis.employee_get_booking_info),
        path('api/employee/booking/complete/', apis.employee_complete_booking),
        path('api/employee/revenue/', apis.employee_get_revenue),
        path('api/employee/location/update/', apis.employee_update_location),

]

tribarbDesktop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url



urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('authentication.urls')),
    path('', include('dashboard.urls')),

    url(r'^api/social/', include('rest_framework_social_oauth2.urls')),
]

dashboard/models.py
from django.db import models
from django.contrib.auth.models import User
from authentication.models import Shop
from django.utils import timezone


class Customer(models.Model):
	user = models.OneToOneField(User, on_delete=models.CASCADE, related_name='customer')
	avatar = models.CharField(max_length=500, default="")
	email = models.CharField(max_length=500, default="")
	stripe_id = models.CharField(max_length=500, default="")
	phone = models.CharField(max_length=500, default="")
	address = models.CharField(max_length=500, blank = True, default="")
	last_logged_in_as = models.BooleanField(default=False)

	def __str__(self):
		return str(self.id) + " " + self.user.get_full_name()


class Employee(models.Model):
	shop = models.ForeignKey(Shop, on_delete=models.CASCADE, null=True, blank=True)
	user = models.OneToOneField(User, on_delete=models.CASCADE, related_name='employee')
	email = models.CharField(max_length=500, default="")
	phone = models.CharField(max_length=500, default="")
	avatar = models.CharField(max_length=500, blank = True, default="")
	location = models.CharField(max_length=500, blank = True, default="")
	last_logged_in_as = models.BooleanField(default=False)

	def __str__(self):
		return str(self.id) + " " + self.user.get_full_name() 


class Service(models.Model):
	shop = models.ForeignKey(Shop, on_delete=models.CASCADE)
	service_name = models.CharField(max_length=500, default="")
	short_description = models.CharField(max_length=500, blank = True, default="")
	price = models.FloatField(default=0)
	shop_service = models.BooleanField(default=False)
	home_service = models.BooleanField(default=False)

	def __str__(self):
		return str(self.id) + " " + self.service_name


class ServiceImage(models.Model):
	service = models.ForeignKey(Service, on_delete=models.CASCADE, default=None)
	image = models.ImageField(upload_to='service_images/', blank=True)

	def __str__(self):
		return self.service.service_name



class Booking(models.Model):
	PLACED = 1
	ACCEPTED = 2
	ONTHEWAY = 3
	COMPLETED = 4
	DECLINED = 5
	CANCELLED = 6

	SHOP_BOOKING = 0
	HOME_BOOKING = 1
	
	CASH = 0
	CARD = 1
	

	STATUS_CHOICES = (
		(PLACED, "Placed"),
        (ACCEPTED, "Accepted"),
        (ONTHEWAY, "Barber En Route"),
        (COMPLETED, "Completed"),
		(DECLINED, "Declined"),
		(CANCELLED, "Cancelled"),
    )

	BOOKING_CHOICES = (
		(HOME_BOOKING, "Home"),
        (SHOP_BOOKING, "Shop"),
    )


	PAYMENT_MODE = (
		(CARD, "Card"),
        (CASH, "Cash"),
    )


	booking_type = models.IntegerField(choices = BOOKING_CHOICES, default = SHOP_BOOKING)
	payment_mode = models.IntegerField(choices = PAYMENT_MODE, default = CASH)
	customer = models.ForeignKey(Customer, on_delete=models.CASCADE)
	shop = models.ForeignKey(Shop, on_delete=models.CASCADE)
	employee = models.ForeignKey(Employee, null = True, on_delete=models.CASCADE)
	status = models.IntegerField(choices = STATUS_CHOICES)
	created_at = models.DateTimeField(default = timezone.now)
	requested_time = models.DateTimeField(blank = True, null = True)
	address = models.CharField(max_length=500, blank = True, null = True, default="")
	requests = models.CharField(max_length=500, blank = True, default="")
	accepted_at = models.DateTimeField(blank = True, null = True)
	rating = models.IntegerField(blank=True, default=0)
	service_fee = models.FloatField(default=0)
	subtotal = models.FloatField(default=0)
	total = models.FloatField(default=0)

	def __str__(self):
	    return str(self.id)


class BookingDetail(models.Model):
	booking = models.ForeignKey(Booking, related_name='booking_details', on_delete=models.CASCADE)
	service = models.ForeignKey(Service, on_delete=models.CASCADE)

	def __str__(self):
	    return str(self.id)

templates/db/account.html
{% extends 'db/sidebar.html' %}

{% load widget_tweaks %}

{% block title %}Tribarb | Account{% endblock %}

{% block page %}


<div class="db-items">
    <div class="card mb-4">

        <div class="card-heading db-card-headings">
            <h4 class="card-title text-center db-card-titles">
                Account
            </h4>
        </div>

        <div class="card-body">

            <h5 class="card-title text-left">Shop Info</h5>

            

            <form method="POST" enctype="multipart/form-data"> 
                {% csrf_token %}
                <div class="card">
                    <div class="card-body"> 
                        <div class="text-left mb-3">
                            <input name="visibility" type="checkbox" {% if request.user.shop.visible_on_app %} checked {% endif %} data-toggle="toggle" data-on="Listed in app" data-width="150" data-height="20" data-off="Unlisted in app" data-onstyle="success" data-offstyle="danger">
                        </div>
                        <p>* All {{ request.user.shop.name }} employees must know the <b>Shop ID and Token</b> to login to the Tribarb mobile app.</p>
                        <h6>Shop ID : {{ request.user.shop.id }}</h6>
                        <h6>Token</h6> 
                        <div class="input-group">
                            <input type="text" name="token" id="showToken" class="form-control" value="{{ request.user.shop.token }}">
                            <span class="input-group-btn">
                                <button type="button" id="generateToken" class="btn btn-warning">
                                    <i class="fa fa-search">Generate Token</i>
                                </button>
                            </span>
                        </div>
                    </div>
                </div>
        
                <div class="row mt-3">
                    <div class="col-sm-6">
                        <h6>Instagram ID</h6>
                        <input type="text" name="instagram" class="form-control" value="{{ request.user.shop.instagram }}" placeholder="Instagram ID">
                    </div>

                    <div class="col-sm-6">
                        <h6>Facebook @</h6>
                        <input type="text" name="facebook" class="form-control" value="{{ request.user.shop.facebook }}" placeholder="Facebook @">   
                    </div>
                </div>
                
                <h6 class="mt-3">Name</h6>
                <div class="form-group">
                    {% render_field shop_form.name class="form-control" %}
                </div>

                <h6>Phone Number</h6>
                <div class="form-group">
                    {% render_field shop_form.phone type="number" class="form-control" %}
                </div>

                <h6>Address</h6>
                <div class="form-group">
                    {% render_field shop_form.address id="address" class="form-control" placeholder="Shop Address"%}   
                    <div style="padding-top: 5px; padding-bottom: 5px;">
                        <input id="submit" type="button" value="Search Address" class="font-weight-normal btn btn-sm btn-block btn-warning"/>  
                    </div>
                    <div style="border-radius: 5px;" id="map" ></div>                           
                </div>

                <h6>Logo</h6>
                {% render_field shop_form.logo %} 
          
                <div class="row">
                    <div class="col-sm-6">
                      <div class="card text-center" style="border: none;">
                        <div class="card-body">
                          <h6 class="card-title">Shop Bookings</h6>
                          {% render_field shop_form.shop_bookings data-toggle="toggle" data-on="Accepted" data-off="Unaccepted"  data-offstyle="danger" %}
                        </div>
                      </div>
                    </div>
                    <div class="col-sm-6">
                      <div class="card text-center" style="border: none;">
                        <div class="card-body">
                          <h6 class="card-title">Home Bookings</h6>
                          {% render_field shop_form.home_bookings data-toggle="toggle" data-on="Accepted" data-off="Unaccepted"  data-offstyle="danger" %}
                        </div>
                      </div>
                    </div>
                </div>


                <h5 class="card-title text-left mt-5">User Info</h5>

                <div class="row">
                    <div class="col-sm-4">
                        <h6>First Name</h6>
                        {% render_field user_form.first_name class="form-control" %} 
                    </div>

                    <div class="col-sm-4">
                        <h6>Last Name</h6>
                        {% render_field user_form.last_name class="form-control" %} 
                    </div>

                    <div class="col-sm-4">
                        <h6>Email</h6>
                        {% render_field user_form.email class="form-control" %} 
                    </div>
                </div>

                <div class="text-center" style="padding-top: 20px;">
                    <button type="submit" class="btn btn-md btn-block btn-primary" >Update</button>
                </div>
            </form>
        </div>
    </div>
</div>


<script>
    $( document ).ready(function() {

        // set the length of the string
        var stringLength = 15;

        // list containing characters for the random string
        var stringArray = ['0','1','2','3','4','5','6','7','8','9','a','b','c','d','e','f','g','h','i','j','k','l','m','n','o','p','q','r','s','t','u','v','w','x','y','z','A','B','C','D','E','F','G','H','I','J','K','L','M','N','O','P','Q','R','S','T','U','V','W','X','Y','Z','!','?'];

        $("#generateToken").click(function (){
            
            var rndString = "";
        
            // build a string with random characters
            for (var i = 1; i < stringLength; i++) { 
                var rndNum = Math.ceil(Math.random() * stringArray.length) - 1;
                rndString = rndString + stringArray[rndNum];
            };
            
            $("#showToken").val(rndString);

        });

    });
</script>

<script src="https://polyfill.io/v3/polyfill.min.js?features=default"></script>

<script defer src="https://maps.googleapis.com/maps/api/js?key={{ mapsKey }}&callback=initMap"></script>

<script>
    let marker; 
  
    function initMap() {
        const geocoder = new google.maps.Geocoder();
        const myLatlng = { lat: 54, lng: -3 };

        map = new google.maps.Map(document.getElementById("map"), {
            zoom: 4,
            center: myLatlng,
        });

        if (document.getElementById("address").value != "") {
            geocodeAddress(geocoder, map);
        }

        map.addListener("click", (mapsMouseEvent) => {
            reverseGeocode(geocoder, map, mapsMouseEvent.latLng)
        });

        document.getElementById("submit").addEventListener("click", () => {
            geocodeAddress(geocoder, map);
        });  
    }


    function geocodeAddress(geocoder, resultsMap) {
        
        if (marker != undefined) {
            marker.setMap(null)
        } 

        resultsMap.setZoom(15)
        const address = document.getElementById("address").value;
        geocoder.geocode({ address: address }, (results, status) => {
            if (status === "OK") {
                resultsMap.setCenter(results[0].geometry.location);
                marker = new google.maps.Marker({
                    map: resultsMap,
                    position: results[0].geometry.location,
                });
            } else {
                alert(
                    "Geocode was not successful for the following reason: " + status
                );
            }
        });
    }


    function reverseGeocode(geocoder, map, latlng) {
        if (marker != undefined) {
            marker.setMap(null)
        } 
        
        geocoder.geocode({ location: latlng }, (results, status) => {
        if (status === "OK") {
            if (results[0]) {
            document.getElementById("address").value = results[0].formatted_address
            marker = new google.maps.Marker({
                position: latlng,
                map,
            });
            map.setZoom(15)
            map.setCenter(latlng)
            
            } else {
            window.alert("No results found");
            }
        } else {
            window.alert("Geocoder failed due to: " + status);
        }
        });
    }
</script>

{% endblock %}

templates/db/add_services.html
{% extends 'db/sidebar.html' %}

{% block title %}Tribarb | Add Service{% endblock %}

{% block page %}


<div class="db-items">
<div class="card mb-4">
    <div class="card-heading db-card-headings">
        <h4 class="card-title text-center db-card-titles">
            Add Service
        </h4>
        
    </div>
    
    <div class="card-body">

        <div id="alertsView" class="alert alert-danger" style="display: none;">
            <p class="danger" id="fieldsAlert"></p>
            <p class="danger" id="checkAlert"></p>
        </div>
        <p>* indicates required field</p>
        
        <label>Service Name *</label>
        <input type="text" id="service_name" class="form-control">

        <label class="mt-4">Description * <em>(350 characters maximum)</em></label>
        <textarea id="short_description" class="form-control" maxlength="350"></textarea>

        <label class="mt-4">Price *</label>
        <input type="number" id="price" class="form-control">

        <p class="mt-4">Service Type * (Tick one or both)</p>
        <input type="checkbox" id="shopService" value="shop" {% if request.user.shop.shop_bookings and not request.user.shop.home_bookings %} checked {% endif %}>
            <label>Shop Service</label><br>
        <input type="checkbox" id="homeService" value="home" {% if not request.user.shop.shop_bookings and request.user.shop.home_bookings %} checked {% endif %}>
            <label>Home Service</label>

        <p class="mt-4">Images</p>
        <input type="file" multiple>

        <div class="text-center">
            <button type="button" id="saveBtn" class="btn btn-primary btn-block mt-4">Add</button>
        </div>

    </div>
</div>
</div>


<script>
    const button = document.getElementById('saveBtn')

    document.addEventListener('DOMContentLoaded', function() {
        var files = []
        FilePond.registerPlugin(FilePondPluginFileValidateSize);
        FilePond.registerPlugin(FilePondPluginFileValidateType);
        FilePond.setOptions({
            allowMultiple:true,
            maxFiles:30,
            maxFileSize: '30MB'
        })
        const inputElement = document.querySelector('input[type="file"]');
        const pond = FilePond.create( inputElement, {
            acceptedFileTypes:['image/png', 'image/jpeg'],
            onaddfile: (err, fileItem) => {
                if (!err) {
                files.push(fileItem.file)
                }
                console.log(files)
            },
            onremovefile: (err, fileItem) => {
                const index = files.indexOf(fileItem.file)
                if (index > -1) {
                    files.splice(index, 1)
                }
                console.log(files)
            }
        } );

        var formData = new FormData();
        $(document).on('click', '#saveBtn', function(e) {
            var has_error = false
            var title = $('#service_name').val()
            var desc =  $('#short_description').val()
            var price = $('#price').val()

            if (title.length == 0 || desc.length == 0 || price.length == 0) {
                $("#alertsView").show()
                document.getElementById("fieldsAlert").innerHTML = 'Please fill in all required fields.';
                has_error = true
            }
            
            if(!document.getElementById('shopService').checked && !document.getElementById('homeService').checked) {
                $("#alertsView").show()
                document.getElementById("checkAlert").innerHTML = 'Please select the service type(s).';
                has_error = true
            }

            if (has_error == false) {
                button.disabled = true
                button.innerHTML = 'Uploading service. Please wait...';
            
            
                if(document.getElementById('shopService').checked) {
                    formData.append('shopService', $('#shopService').val())
                } else {
                    formData.append('shopService', null)
                }

                if(document.getElementById('homeService').checked) {
                    formData.append('homeService', $('#homeService').val())
                } else {
                    formData.append('homeService', null)
                }

                formData.append('length', files.length)
                formData.append('service_name', $('#service_name').val())
                formData.append('short_description', $('#short_description').val())
                formData.append('price', $('#price').val())
                for (var i = 0; i < files.length; i++) {
                    formData.append('images' + i, files[i])
                }
                formData.append('csrfmiddlewaretoken', '{{ csrf_token }}')

                $.ajax({
                    type: 'POST',
                    url: '{% url "shop-add-services" %}',
                    data: formData,
                    cache: false,
                    processData: false,
                    contentType: false,
                    enctype: 'multipart/form-data',
                    success: function (){
                        window.location.href = "{% url 'shop-services' %}";
                    },
                    error: function(data) {
                        console.log(data)
                        button.disabled = false
                        button.innerHTML = "Add"
                    
                    }
                })
            }      
        })
    })
</script>


{% endblock %}

templates/db/booking.html
{% extends 'db/sidebar.html' %}

{% block title %}Tribarb | Booking #{{ booking.id }}{% endblock %}

{% block page %}

<div class="db-items">
    <div class="card mb-4">

        <div class="card-heading db-card-headings">
            <h4 class="card-title text-center db-card-titles">
                Booking #{{ booking.id }} 
            </h4>
            <h5 class="card-title text-center" style="color: whitesmoke;">
                Status : {{ booking.get_status_display  }} 
            </h5>
        </div>

        <div class="card-body text-center">
            <div class="mb-4 ">
                <div class="table-responsive">
                    <table class="table table-sm text-center table-bordered">

                        <thead class="db-card-headings db-card-titles">
                            <tr>
                                <th scope="col">Requested Services</th>
                                <th scope="col">Price</th>
                            </tr>
                        </thead>
                        
                        <tbody>
                            {% for bd in booking.booking_details.all %}
                                <tr>
                                    <td>{{ bd.service.service_name }}</td>
                                    <td>£{{  bd.service.price|floatformat:2  }}</td>
                                </tr>
                            {% endfor %}

                            <tr>
                                <td><b>Service Fee</b></td>
                                <td>£{{  booking.service_fee|floatformat:2  }}</td>
                            </tr>

                            <tr>
                                <td><b>Total</b></td>
                                <td>£{{  booking.total|floatformat:2  }}</td>
                            </tr>
                        </tbody>
                    </table>
                </div>
            </div>


            <div class="mb-4">
                <h6>Customer Name </h6>
                <p>{{ booking.customer }}</p>
            </div>

            <div class="mb-4">
                <h6>Booking Type </h6>
                <p>{{ booking.get_booking_type_display }}</p>
            </div>

            <div class="mb-4">
                <h6>Booking Date & Time</h6>
                <p>{{ booking.requested_time }}</p>
            </div>

            {% if booking.booking_type == 1 %}
                <div class="mb-4">
                    <h6>Customer Address</h6>
                    <p>{{ booking.address }}</p>
                </div>
            {% endif %}

            <div class="mb-4">
                <h6>Assigned Employee</h6>
                <p>{{ booking.employee }}</p>
            </div>

            <div class="mb-4">
                <h6>Payment Mode</h6>
                <p>{{ booking.get_payment_mode_display }}</p>
            </div>

            {% if booking.requests != "" %}
                <div class="mb-4">
                    <h6>Additional Requests</h6>
                    <p>{{ booking.requests }}</p>
                </div>
            {% endif %}
        </div>
    </div>
</div>

{% endblock %}

templates/db/bookings.html
{% extends 'db/sidebar.html' %}

{% block title %}Tribarb | Bookings{% endblock %}

{% block page %}

<div class="db-items">
    <div class="card mb-4">

        <div class="card-heading db-card-headings">
            <h4 class="card-title text-center db-card-titles">
                Current Bookings
            </h4>
        </div>

        <div class="card-body">
            <div class="table-responsive">
                <table class="table table-bordered text-center">

                    <thead>
                        <tr class="db-card-headings db-card-titles">
                            <th>#</th>
                            <th>Customer</th>
                            <th>Booking Type</th>
                            <th>Requested Date & Time</th>
                            <th>Employee</th>
                            <th>Status</th>
                        </tr>
                    </thead>

                    <tbody>

                        {% for booking in bookings %}
                        {% if booking.status != 4 and booking.status != 5 and booking.status != 6 %}
                            <tr>
                                <td><a href="{% url 'shop-view-booking' booking.id %}">{{ booking.id }}</a></td>
                                <td>{{ booking.customer.user.get_full_name }}</td>
                                <td>{{ booking.get_booking_type_display}}</td>
                                <td>{{ booking.requested_time }}</td>

                                {% if booking.employee == None %}
                                    <td>None</td>
                                {% endif %}
                                {% if booking.employee != None %}
                                    <td>{{ booking.employee.user.get_full_name }}</td>
                                {% endif %}
                            
                                <td class="font-weight-bold">{{ booking.get_status_display }}</td>
                            </tr>
                        {% endif %}
                        {% endfor %}

                    </tbody>

                </table>
            </div>

            

            <div class="text-center">
                {% if bookings.count == 0 %}
                    <p class="mb-3" style="color: gray;">Your ongoing bookings will appear here.</p>
                {% endif %}
                <a href="{% url 'shop-bookings-completed' %}" class="btn btn-block btn-primary">View Past Bookings</a>
            </div>

        </div>
    </div>
</div>

{% endblock %}

templates/db/bookings_completed.html
{% extends 'db/sidebar.html' %}

{% block title %}Tribarb | Bookings{% endblock %}

{% block page %}

<div class="db-items">
    <div class="card mb-4">

        <div class="card-heading db-card-headings">
            <h4 class="card-title text-center db-card-titles">
                Previous Bookings
            </h4>
        </div>

        <div class="card-body">
            <div class="table-responsive">
                <table class="table table-bordered text-center">

                    <thead>
                        <tr class="db-card-headings db-card-titles">
                            <th>#</th>
                            <th>Customer</th>
                            <th>Booking Type</th>
                            <th>Requested Date & Time</th>
                            <th>Assigned Employee</th>
                            <th>Status</th>
                        </tr>
                    </thead>

                    <tbody>
                        {% for booking in booking %}
                        {% if booking.status == 4 or booking.status == 5 or booking.status == 6 %}
                            <tr>
                                <td><a href="{% url 'shop-view-booking' booking.id %}">{{ booking.id }}</a></td>
                                <td>{{ booking.customer.user.get_full_name }}</td>
                                <td>{{ booking.get_booking_type_display}}</td>
                                <td>{{ booking.requested_time }}</td>
                        
                                {% if booking.employee == None %}
                                    <td>None</td>
                                {% endif %}
                                {% if booking.employee != None %}
                                    <td>{{ booking.employee.user.get_full_name }}</td>
                                {% endif %}

                                <td class="font-weight-bold">{{ booking.get_status_display }}</td>  
                            </tr>
                        {% endif %}
                        {% endfor %}
                    </tbody>
                </table>
            </div>

            <div class="text-center">
                {% if booking.count == 0 %}
                    <p style="color: gray;">Your previous bookings will appear here.</p>
                {% endif %}
            </div>
        </div>
    </div>
</div>

{% endblock %}

templates/db/service_album.html
{% extends 'db/sidebar.html' %}

{% block title %}Tribarb | Service Album{% endblock %}

{% block page %}

<div class="db-items">
    <div class="card mb-4">

        <div class="card-heading db-card-headings">
            <h4 class="card-title text-center db-card-titles">
                {{ service.service_name }} Album
            </h4>
        </div>
        
        <div class="card-body">
            <div class="album py-5">
                <div class="container">
                    <div class="row">
                    {% for p in photos %}
                        <div class="col-md-4">
                            <div class="card mb-4 box-shadow">
                                <img class="card-img-top" src="{{p.image.url}}" alt="Card image cap">
                            </div>
                        </div>
                    {% endfor %}
                    </div>
                </div>
            </div>

            <div class="text-center">
                <a href="{% url 'shop-edit-services' service.id %}" class="btn btn-block btn-primary">Edit Album</a>
            </div>

        </div>  
    </div>
</div>
 
{% endblock %}